// Copyright 2023 Ubie, inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// PersonalAccessToken represents a personal access token in Lightdash
type PersonalAccessToken struct {
	UUID        string  `json:"uuid"`
	Description string  `json:"description"`
	CreatedAt   string  `json:"createdAt"`
	ExpiresAt   *string `json:"expiresAt"`
	RotatedAt   *string `json:"rotatedAt"`
	LastUsedAt  *string `json:"lastUsedAt"`
}

// PersonalAccessTokenWithToken includes the token value (only returned on creation)
type PersonalAccessTokenWithToken struct {
	PersonalAccessToken
	Token string `json:"token"`
}

// CreatePersonalAccessToken represents the request body for creating a personal access token
type CreatePersonalAccessToken struct {
	Description   string  `json:"description"`
	ExpiresAt     *string `json:"expiresAt"`
	AutoGenerated bool    `json:"autoGenerated"`
}
